import { ShieldAlert } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 space-y-8">
      <div className="text-center space-y-3">
        <div className="w-10 h-10 rounded-full bg-cyan-950/20 border border-cyan-800/10 flex items-center justify-center mx-auto">
          <ShieldAlert className="w-5 h-5 text-cyan-400" />
        </div>
        <h1 className="text-2xl md:text-4xl font-extrabold text-white">Terms of Service</h1>
        <p className="text-[10px] text-slate-500 uppercase tracking-widest">Effective date: July 10, 2026</p>
      </div>

      <div className="glass-panel p-8 rounded-3xl border border-slate-900 text-xs text-slate-400 leading-relaxed space-y-6">
        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-200 uppercase tracking-wider">1. Appointment Booking & Retention Fees</h2>
          <p>
            By booking a slot on our scheduling wizard, you confirm that all patient contact information provided is authentic. Because our surgeons block clinical suits and custom CAD/CAM milling resources for your reservation, late cancellations made under 24 hours may incur a reservation fee.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-200 uppercase tracking-wider">2. Medical Diagnostic Disclaimer</h2>
          <p>
            Assessments generated by our AI Symptom Checker and chatbot are purely educational, designed to cross-reference your descriptions with clinic service matches. These analysis reports do NOT constitute final medical diagnoses. Symmetrical dental evaluations require physical examination and 3D Cone Beam X-Rays performed by licensed directors.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-200 uppercase tracking-wider">3. Treatment Pricing & Estimations</h2>
          <p>
            Costs listed in our fee catalog represent starting base estimates. Symmetrical smile design packages may require custom material volumes, bone graft reinforcements, or specific adjustments which will be reviewed in detail during your physical consult prior to procedure commencement.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-200 uppercase tracking-wider">4. Governing Law</h2>
          <p>
            These clinical terms are governed by the laws of the State of California. Any disputes arising from services performed at Aura Luxury Clinics will be settled under binding arbitration in Beverly Hills, Los Angeles County.
          </p>
        </section>
      </div>
    </div>
  );
}
